### ISSUE TITLE
Git Clone throws `NoSuchMethodError: ‘java.nio.file.Path io.kestra.core.runners.RunContext.tempDir()’`

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-github#10]
Git clone is broken, not sure whether Git or WorkingDirectory task is the issue?

**This is a blocker as it breaks tutorial flows + Git tasks are critical for many deployments of our users**

error:

```bash
Clone_repository
2024-08-02 12:48:00.439tutorialdwh_and_analyticsclone_repository6k2Fces1qn6i863RudaHlv‘java.nio.file.Path io.kestra.core.runners.RunContext.tempDir()’
Clone_repository
2024-08-02 12:48:00.439[tutorial](http://localhost:28080/ui/flows?namespace=tutorial)dwh_and_analyticsclone_repository6k2Fces1qn6i863RudaHlvjava.lang.NoSuchMethodError: ‘java.nio.file.Path io.kestra.core.runners.RunContext.tempDir()’
 at io.kestra.plugin.git.Clone.run(Clone.java:103)
 at io.kestra.plugin.git.Clone.run(Clone.java:19)
 at io.kestra.core.runners.WorkerTaskThread.doRun(WorkerTaskThread.java:76)
 at io.kestra.core.runners.AbstractWorkerThread.run(AbstractWorkerThread.java:57)
```

reproducer:
```yaml
id: dwh_and_analytics
namespace: tutorial
description: Data Warehouse and Analytics

tasks:
  - id: dbt
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
    - id: clone_repository
      type: io.kestra.plugin.git.Clone
      url: https://github.com/kestra-io/dbt-demo
      branch: main

    - id: dbt_build
      type: io.kestra.plugin.dbt.cli.DbtCLI
      taskRunner:
        type: io.kestra.plugin.scripts.runner.docker.Docker
      containerImage: ghcr.io/kestra-io/dbt-duckdb:latest
      commands:
        - dbt deps
        - dbt build
      profiles: |
        jaffle_shop:
          outputs:
            dev:
              type: duckdb
              path: dbt.duckdb
              extensions: 
                - parquet
              fixed_retries: 1
              threads: 16
              timeout_seconds: 300
          target: dev      

    - id: python
      type: io.kestra.plugin.scripts.python.Script
      outputFiles:
        - "*.csv"
      taskRunner:
        type: io.kestra.plugin.scripts.runner.docker.Docker
      containerImage: ghcr.io/kestra-io/duckdb:latest
      script: |
        import duckdb
        import pandas as pd

        conn = duckdb.connect(database='dbt.duckdb', read_only=False)

        tables_query = "SELECT table_name FROM information_schema.tables WHERE table_schema = 'main';"
        tables = conn.execute(tables_query).fetchall()

        # Export each table to CSV, excluding tables that start with 'raw' or 'stg'
        for table_name in tables:
            table_name = table_name[0]
            # Skip tables with names starting with 'raw' or 'stg'
            if not table_name.startswith('raw') and not table_name.startswith('stg'):
                query = f"SELECT * FROM {table_name}"
                df = conn.execute(query).fetchdf()
                df.to_csv(f"{table_name}.csv", index=False)

        conn.close()
```
