### ISSUE TITLE
Search tasks are returning ions one after the other making it impossible to query the attributes

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/plugin-github#21]
### Expected Behavior

The result of the search task should be queryable via Pebble expression.

### Actual Behaviour

The Github Repos Search task is giving out result as follows:
```
{name:"superset",description:"Apache Superset is a Data Visualization and Data Exploration Platform",owner:null,updated:2024-08-21T03:15:07.000Z,created:2015-07-21T18:55:34.000Z,language:"TypeScript",full_name:"apache/superset",url:"https://github.com/apache/superset",task_count:13346,stars_count:61278,pull_request_count:0,issues_count:934}
{name:"echarts",description:"Apache ECharts is a powerful, interactive charting and data visualization library for browser",owner:null,updated:2024-08-21T03:00:22.000Z,created:2013-04-03T03:18:59.000Z,language:"TypeScript",full_name:"apache/echarts",url:"https://github.com/apache/echarts",task_count:19590,stars_count:59968,pull_request_count:0,issues_count:2210}
```

I am unable to query the name from these results. Lets say I want only the list of repository names:
```
superset
echarts
```
I am unable to get it using the Pebble expression. 
I am not sure if it is the problem with the result output, or I am unable to get the correct Pebble expression to extract the names.

### Steps To Reproduce

1. Use the example flow to get the Github Repos Search result.
2. Try to extract the names from the result. I am unable to do it.

### Environment Information

- Kestra Version: 0.18.1
- Plugin version: 0.18.1
- Operating System (OS / Docker / Kubernetes):  Docker
- Java Version (If not docker):

### Example flow

```
id: github_repos
namespace: company.team
tasks:
  - id: top_apache_repos_java
    type: io.kestra.plugin.github.repositories.Search
    query: "org:apache stars:>10000"
    language: java
    visibility: PUBLIC
    sort: STARS
    order: DESC
```

**Comment by eddiejaoude** [comment]
I can verify I have the same issue with Kestra `0.22.8`. 

 switched to using GitHub's API as a work around, here is an example:

```yml
- id: get_issues
   type: io.kestra.plugin.core.http.Request
   uri:  https://api.github.com/repos/{{ vars.REPO_OWNER }}/{{ vars.REPO_NAME }}/issues
   method: GET
   headers:
     Accept: application/vnd.github+json
     X-GitHub-Api-Version: 2022-11-28
```
