### ISSUE TITLE
Add task to create a comment on a GitHub issue

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/plugin-github#3]
```yaml
id: myflow
namespace: company.myteam

tasks:
  - id: hello
    type: io.kestra.plugin.github.issues.CreateComment
    token: your_github_token
    repository: kestra-io/kestra
    issueNumber: 1234    
    body: "{{ execution.id }} has failed on {{ taskrun.startDate }}. See the link below for more details"
```
