### ISSUE TITLE
Add task to create a pull request from a source to a destination branch

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-github#4]
### Feature description

```yaml
id: myflow
namespace: company.myteam

tasks:
  - id: pr
    type: io.kestra.plugin.github.pulls.Create
    token: your_github_token
    repository: kestra-io/kestra
    sourceBranch: feat/myfeature
    targetBranch: main
    title: Add new flows
    body: New workflows can be merged
```

Docs: https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#create-a-pull-request

Python equivalent:

```Python
import requests

# Replace with your own values
owner = 'repository_owner'
repo = 'repository_name'
head_branch = 'feature-branch'  # The branch where your changes are implemented
base_branch = 'main'  # The branch you want to merge into
title = 'Pull request title'
body = 'Description of the pull request'
token = 'your_personal_access_token'

url = f'https://api.github.com/repos/{owner}/{repo}/pulls'

headers = {
    'Authorization': f'token {token}',
    'Accept': 'application/vnd.github.v3+json'
}

pull_request_data = {
    'title': title,
    'head': head_branch,
    'base': base_branch,
    'body': body
}

response = requests.post(url, headers=headers, json=pull_request_data)

if response.status_code == 201:
    print('Pull request created successfully.')
else:
    print('Failed to create pull request:', response.json())
```
